### ISSUE TITLE
Paginated archives >1 canonicalize to page 1

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/boldgrid-seo#14]
**Describe the bug**
On paginated archives, any page greater than 1 has a canonical link back to the first page. This prevents indexing of any more than the first X links for any given taxonomy, where X is determined by the theme's pagination logic.

**To Reproduce**
1. Go to the second page of any paginated archive, for example on [boldgrid.com](https://www.boldgrid.com/support/category/cloud-wordpress/page/2/)
2. View the source and Ctrl-F for "Canonical"
3. Note that the canonical URL points to the first page of the archive.

**Expected behavior**
BoldGrid's [competitors](https://yoast.com/pagination-seo-best-practices/) as well as [SEO specialists](https://moz.com/blog/seo-guide-to-google-webmaster-recommendations-for-pagination) believe that paginated lists of links should self-canonicalize, and not rely on rel='next' or rel='prev' for crawling purposes (other than as needed for accessibility).

**Additional context**
This seems to be related to these [types](https://github.com/BoldGrid/boldgrid-seo/blob/a4b5d2f7791383a5cf7b1b38aae077342a788113/includes/class-boldgrid-seo-util.php#L226) of [lines](https://github.com/BoldGrid/boldgrid-seo/blob/a4b5d2f7791383a5cf7b1b38aae077342a788113/includes/class-boldgrid-seo-util.php#L237) using get_term_link, get_search_link, get_post_type_archive_link. The comments suggest that this approach was inspired by All in One SEO, however the  wp_get_canonical_url() will more likely be useful than manually fetching the link based on the specific taxonomy and ignoring pagination.

**Comment by bwmarkle** [comment]
@harryjackson1221 are we ready to release this change, or if I remember, did you have some concerns?
