### ISSUE TITLE
Bug Report: Image detection problems

### ISSUE THREAD

**Issue by boldgrid-support** [BoldGrid/boldgrid-seo#2]
### **Description** ###
Suggestion to 'Try adding at least one image that's relevant to your content's topic to further optimize your page' shows as negative, even when there are multiple images in the page content.

**WordPress Version**: 5.0.2
**Easy SEO Version**: 1.6.0
**Browser**: Firefox & Chrome

**Comment by bwmarkle** [comment]
Tested, cannot replicate.

Can you provide example page content that isn't working?

**Comment by bwmarkle** [comment]
I think the issue can be traced back to [Adding Gutenberg support](https://github.com/BoldGrid/boldgrid-seo/commit/10dcac897164407d99ecaba28e7561a9478b0475) on Nov 19.

My fix, which needs testing, can be found here - https://github.com/BoldGrid/boldgrid-seo/commit/7286b64592096abe2f747125121051c9d5a591cc Can anyone help test?

Seems to fix the image issue, both on Gutenberg and classic editor.

The other change in the code affects the h1 and h2 tag info, which seems off. Was that always an issue?

**Comment by rramo012** [comment]
The content is wrapped in a div before `.find` because it will not include the highest ancestor in the queried content. For example if the content only contains `<h1>My Title</h1>`. Find return 0 matches for h1.
