### ISSUE TITLE
Add Sitemap Generator Tool

### ISSUE THREAD

**Issue by john-paulb** [BoldGrid/boldgrid-seo#23]
Please consider adding a tool to BG SEO that will generate a sitemap, similar to Yoast. For example, we want to generate a sitemap for the support center but BG SEO doesn't allow this. Someone in the meeting suggested using Yoast SEO, but I declined this since SEO plugins sometimes do not play nice with each other.

**Comment by nicolepaschen** [comment]
Hello, we have an open ticket for this feature already :) 
https://github.com/BoldGrid/boldgrid-seo/issues/16
