### ISSUE TITLE
Conflict with BoldGrid Easy SEO causes blank metabox

### ISSUE THREAD

**Issue by timelsass** [BoldGrid/boldgrid-seo#3]
**Describe the bug**
Originally reported issue here: Yoast/wordpress-seo#11980 and moved to wp.org: https://wordpress.org/support/topic/conflict-with-yoast-seo-33/

Please give us a description of what happened.
When the BoldGrid Easy SEO plugin is active, along with the Post and Page Builder by BoldGrid, the Yoast meta box shows blank. The JavaScript error below appears in the browser's console:
Uncaught TypeError: Cannot read property 'getEditedPostAttribute' of undefined bgseo.min.js?ver=1.6.0:1

**Please describe what you expected to happen and why.**
No JavaScript errors to appear and the Yoast metabox to load properly.

**How can we reproduce this behavior?**
- Install BoldGrid Easy SEO and Post and Page Builder
- Create a new post
- Note that the Yoast metabox shows blank and the aforementioned error shows up in the browser's console

**Used versions**
- WordPress version: 5.0.2
- Yoast SEO version: 9.3
- BoldGrid Easy SEO v1.6.0
- Post and Page Builder v1.9.2
- Tested with theme: Twenty Nineteen

**Comment by rramo012** [comment]
This issue is being addressed with https://github.com/BoldGrid/boldgrid-seo/commit/7c93b52f15a6060677a3f534a449f6426a40bedd
