### ISSUE TITLE
Red / Yellow / Green indicators missing in WordPress 5.5

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-seo#31]
When using WordPress 5.4 and the stable version of SEO plugin, I see this. There are colored circles and text as expected:
![seo-54](https://user-images.githubusercontent.com/20601160/90540881-d62a8c00-e14f-11ea-8be0-55976e3f11a1.PNG)

When using WordPress 5.5, the color circles and associated text do now show on any of the 3 tabs.
![seo-55](https://user-images.githubusercontent.com/20601160/90540880-d591f580-e14f-11ea-983f-e239298ce32a.PNG)

In 5.4 the bgseo-analysis div has content:
![bgseo-analysis-54](https://user-images.githubusercontent.com/20601160/90541243-50f3a700-e150-11ea-981c-54f2a1af2971.PNG)

Which is missing from 5.5:
![bgseo-analysis-55](https://user-images.githubusercontent.com/20601160/90541248-50f3a700-e150-11ea-84df-419b1cd243a3.PNG)

**Comment by jessecowens** [comment]
The lights work with the WordPress Editor, this issue only occurs on PPB and Classic Editors.

**Comment by bwmarkle** [comment]
@nicolepaschen and @jessecowens can you two test the changes?

**Comment by nicolepaschen** [comment]
We both reviewed and think it's good to release, thanks!
