### ISSUE TITLE
[Bug] Content Word Count is not Updated 

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/boldgrid-seo#42]
**Describe the bug**
The "Stoplight" for content length remains red with "You haven't entered any content yet!" regardless of how many words are in the post or page. 

**To Reproduce**
1. Install WordPress with BoldGrid Easy SEO
2. Create a post or page and enter in any amount of content
3. Note that the word count remains zero
4. Save Draft or Publish, and note that the word count remains zero.

**Expected behavior**
The word count should continue to update via Ajax process, and after saving a draft or publishing
**Screenshots**
![image](https://user-images.githubusercontent.com/8019842/108274351-015b5b80-7132-11eb-96f5-582d83ae6685.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
This issue was [reported in the BoldGrid User Forums](https://www.boldgrid.com/support/question/social-image-content-word-count-are-not-updating/).

**Comment by jessecowens** [comment]
This issue only occurs using the Post and Page Builder or Classic TinyMCE editor, word count works as expected using WordPress "Gutenberg" editor.

**Comment by joe9663** [comment]
[+1 for this fix from the forums](https://www.boldgrid.com/support/boldgrid-easy-seo-plugin-product-guide/keywords/#comment-9754)

**Comment by sovamind** [comment]
Just a bump to let you know this is still an issue.  I spent nearly 45m trying to figure out why it kept saying that I needed to add content until I finally found this bug report.  Any ETA on a fix?
